services:
  app:
    image: node:24.10.0
    command: sh -c "npm install && npm run start:debug"
    container_name: binance-analysis-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app:delegated
      - /usr/src/app/node_modules
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - db

  db:
    image: mongo:7
    container_name: binance-analysis-db
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=binance-analysis_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
